### ISSUE TITLE
Selecting checkbox input breaks display

### ISSUE THREAD

**Issue by hafen** [trelliscope/trelliscopejs-lib#1049]
To reproduce:

Go here: file:///Users/rhafen/Documents/Code/trelliscope-new/examples/docs/lego/index.html and select "I want it" and the page will fail.

![Image](https://github.com/trelliscope/trelliscopejs-lib/assets/1275592/fc90a7d3-fbac-4548-8083-627489197625)

Example files are here:

https://github.com/trelliscope/examples/tree/main/examples/lego

**Comment by Incin** [comment]
issue in the data not being an array
