### ISSUE TITLE
If you use the embed version and expand the view, then condense the view it breaks and the whole app disappears.

### ISSUE THREAD

**Issue by Incin** [trelliscope/trelliscopejs-lib#310]

**Comment by hafen** [comment]
On this topic, what do you guys think of using `requestFullScreen()` instead of the current approach of filling the window?

**Comment by jefferymills** [comment]
I had actually thought the same thing when I first encountered that functionality. It does behave a little differently in practice. It will actually take up the full screen not just the browser window and the user presses escape to exit fullscreen. But I'm personally in favor of it.
