### ISSUE TITLE
Create new Panel component

### ISSUE THREAD

**Issue by jefferymills** [trelliscope/trelliscopejs-lib#428]

**Comment by hafen** [comment]
Here are the rules for creating a URL that an `img` or `iframe` tag can point to:

If in displayInfo.json you see the following:

```json
  "panel_type": "img",
  "panel_format": "png" (or any other valid file extension)
```

or:

```json
  "panel_type": "iframe",
  "panel_format": "html"
```

Then it means that there are local image or html files generated from R. In this case, to build an ing or iframe path for each panel, we need to build the path as follows, with `di` as the displayInfo object, and `md` as the metaData object, and `i` as the index of the row of the meta data that the panel is being plotted for:

```js
const path = `displays/${di.name}/panels/${md.__PANEL_KEY__[i]}.${di.panel_format}`;
```

If you see the following in displayInfo.json:

```json
  "panel_type": "img",
  "panel_format": null
```

or

```json
  "panel_type": "iframe",
  "panel_format": null
```

This means that the full (or relative) path to the asset is completely specified in the meta data and you can get the panel path as follows:

```js
const path = md.__PANEL_KEY__[i];
```

**Comment by jefferymills** [comment]
Will the `panel_format` property always be present but just sometimes contain `null`? Or will the property sometimes not be there?
