### ISSUE TITLE
some bar charts are not rendering correctly, the test one ryan made is incorrect

### ISSUE THREAD

**Issue by Incin** [trelliscope/trelliscopejs-lib#719]

**Comment by hafen** [comment]
![Image](https://user-images.githubusercontent.com/1275592/222253516-087dd1b7-583a-4a9f-9c39-86d26c13fe9a.png)



![Image](https://user-images.githubusercontent.com/1275592/222253573-93750c89-846b-4a03-995a-3699289dbfd3.png)
