### ISSUE TITLE
Figure out layout to resize per Ryan and J's requirements, no half cut off panels

### ISSUE THREAD

**Issue by Incin** [trelliscope/trelliscopejs-lib#730]

**Comment by hafen** [comment]
I think one way to achieve this is the following:

- Only have a control for number of columns.
- Stick with the existing css grid solution that fits the panels to the available width according to the specified number of columns.
- Calculate the row height for the given configuration. For example, if there are 3 columns that are to fill 1000px of available viewport width, and the panel aspect is 1.5, then each panel's width will be something like w = (1000 - 4 * padding) / 3 (this is assuming that the same horizontal padding is applied between panels and between the edges of the viewport and the panels). And then the panel height will be w / 1.5. Then add the labels height (25px * number of labels showing) to get total row height. Then automatically choose number of rows to be the maximum value of nrows such that nrows * panel height does not exceed the viewport height.
- The only exception to this would be when there is just one row, in which case you would want to make sure the panels fit in both the height and width of the viewport.
