### ISSUE TITLE
Issue with capitalization

### ISSUE THREAD

**Issue by hafen** [trelliscope/trelliscopejs-lib#769]
The following display works:

https://hafen.github.io/trelliscope-examples3/magic_trelliscopes2

While this one doesn't:

https://hafen.github.io/trelliscope-examples3/magic_trelliscopes

It's because of capitalization in the display directory name. It would be good for the second example to work.

**Comment by jefferymills** [comment]
Both seem to be working for me locally. Does it have to be built to see the error?

**Comment by hafen** [comment]
It works locally but not when served on GitHub pages.On Mar 17, 2023, at 11:28 AM, Jeff Mills ***@***.***> wrote:﻿
Both seem to be working for me locally. Does it have to be built to see the error?

**Comment by jefferymills** [comment]
Ok, there is a `toLowerCase` on the snakeCase method which I suspect is the issue though I can't test it locally. I will change that and then I guess you can check it when you have time.
