### ISSUE TITLE
Test very large display

### ISSUE THREAD

**Issue by hafen** [trelliscope/trelliscopejs-lib#780]
I added a new example that provides a very large display (1.1 million photos from the Mars rovers). The metaData.jsonp file is >250MB. It's here on GitHub: https://github.com/hafen/trelliscope-examples3/tree/main/mars

I gzipped metaData.jsonp so that it would be easier to commit so you probably need to decompress that before testing.

This provides a good example to test large displays. It takes a long time to load the metadata. On Chrome it works fine but on Safari I get this:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1275592/226684792-1705bfed-e7a3-420f-9460-a171c8efa29d.png">

It might be nice to add a loading spinner. I'm also wondering if in cases like this I should provide a subset of the metadata for the first 10-20 panels so that we can at least show something while the rest is loading. Any thoughts?

**Comment by hafen** [comment]
Another possibility for these very large displays is for me to split metaData up into chunks - maybe 50-100k rows per chunk, and we load them asynchronously and use crossfilter.add to update the data as they are loaded. Thoughts?

**Comment by Incin** [comment]
hmmm i think the ideal solution would be to load it asynchronously especially to lay the foundation in the event a backend is ever implemented. i think this will be good to bring up tomorrow in our meeting too.

**Comment by Incin** [comment]
this is no longer an issue when we looked into the jsonp to js file and speeding up load times
