### ISSUE TITLE
Display panel counts with thousands separators

### ISSUE THREAD

**Issue by hafen** [trelliscope/trelliscopejs-lib#781]
When there are a lot of panels, it's nice to have thousands separators. See the images below for where this is needed.

We should use locale-specific separators.

<img width="213" alt="image" src="https://user-images.githubusercontent.com/1275592/226685323-b39fff21-9c7e-448d-a2be-7e3d0481bf6f.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1275592/226685593-ac22b6fb-af1b-4cbd-bd52-d4f3e5d40359.png">

**Comment by Incin** [comment]
I will run these through our number formatter
