### ISSUE TITLE
Preserve first panels in view when number of rows changes due to UI interactions

### ISSUE THREAD

**Issue by hafen** [trelliscope/trelliscopejs-lib#783]
Here's an example. Open this in a window and resize the window so that two rows are barely able to fit:

https://hafen.github.io/trelliscope-examples3/magic_trelliscopes/#ncol=5&arr=rows&pg=5&labels=name,power&sidebar=3&fv=

<img width="1716" alt="image" src="https://user-images.githubusercontent.com/1275592/226688010-da7ff431-4b10-4881-8936-bd5681ba3274.png">

Now add labels until it switches to one row:

<img width="1716" alt="image" src="https://user-images.githubusercontent.com/1275592/226688210-59cb7cc4-7a6a-402f-ad6b-e614efdf8d37.png">

Ideally the first card visible in the first view "Charge of the Mites" will still be the first card showing in the second view when the number of rows has changed.

@jefferymills this is probably pretty easy to fix based off your latest work on layout.

**Comment by Incin** [comment]
This also seems to be related but if you add a filter and shrink it down you can break the pagination see screenshot


![Image](https://user-images.githubusercontent.com/22066908/226744609-716c1b7e-fdbf-4667-b3bd-774e1cb25e83.png)
