### ISSUE TITLE
Fix inputs that are missing from R package

### ISSUE THREAD

**Issue by Incin** [trelliscope/trelliscopejs-lib#794]
We are missing input options that are available to specify in the R interface. These are the following

- checkbox
- select
- multiselect
- number

Ryan can provide an example that has these specified.

**Comment by hafen** [comment]
You can see the type definitions for these inputs here:

https://github.com/trelliscope/trelliscope/blob/main/inst/types/types.ts#L97-L117

I would base off of the following MUI components for these:

- checkbox: https://mui.com/material-ui/react-checkbox/
- select: https://mui.com/material-ui/react-select/
- multiselect: https://mui.com/material-ui/react-autocomplete/#multiple-values
- number: https://mui.com/material-ui/react-text-field/#type-quot-number-quot

Note that for the number input, min and max are optional. If one or both are provided, we should restrict inputs to those ranges.

Another important thing is that we need to keep the panel labels at their specified maximum height (I think it's `27px`). So we may need to get creative with the size of some of these. It may make most sense for many of these to show a read-only representation of the current value in the panel label with the edit pencil icon and a popover that opens up to provide more space for the input, like we have done with the text input (see image below). We probably will need this for checkbox and multiselect. Maybe even radio to deal with the issue of too many options bleeding outside the available space for the label.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/1275592/228081625-1fff4567-5c2b-4dc8-9418-d82b2820ee81.png">

**Comment by hafen** [comment]
I have made an example with all of these types of inputs here:

https://github.com/hafen/trelliscope-examples3/tree/main/inputs_test
