### ISSUE TITLE
There is not an easy way to tell what filters are applied after they've been removed from the sidebar

### ISSUE THREAD

**Issue by hafen** [trelliscope/trelliscopejs-lib#899]
Here's an example:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/1275592/234718019-06753182-2b74-4a05-bb52-106379a67a20.png">

It said there is one filter applied, but there's no way to tell which one it is. You have to add each variable to the sidebar until you find it.

I think a good way to fix this is to force a variable that has an active filter to always remain in the sidebar. If the filter is active, we can replace the "x" icon that would remove it to a "minimize" icon, "-", which would collapse the filter so that it only shows the filter header (name and label) and maybe a short summary of the filter (kind of like the pills that used to be at the bottom of the app). Then the user could expand the variable to see the full filter view. If they clear the filter, then the minimize button would become the "x" remove button.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1275592/234719750-ab23a299-65d7-49de-88db-bbed7febaa31.png">

**Comment by Incin** [comment]
we decided to do a modal for confirming and whenever a filter is removed it clears it.

**Comment by hafen** [comment]
And the modal should only appear if there is an active filter on the variable that has been closed. Otherwise, just close.
