### ISSUE TITLE
Make column headers more readable

### ISSUE THREAD

**Issue by hafen** [trelliscope/trelliscopejs-lib#901]
If the content of the column is narrow, the column header can get cut off to the point of not being readable. And you also can't see the sort indicator which is important.

There are two possibilities here:

1. Include the column header in the column width calculation so that columns are always wide enough for the column header to be visible.
2. Increase the minimum column width such that at least the sort arrows are always visible.

I'm maybe leaning more toward #2, provided that we can add some tooltips to the column headers (I'll file a separate issue about this).

**Comment by Incin** [comment]
110 min width
