### ISSUE TITLE
Comments have a different background color compared to other panel labels

### ISSUE THREAD

**Issue by hafen** [trelliscope/trelliscopejs-lib#919]
Perhaps this is by design so that they stand out from non-input labels?

<img width="443" alt="Screenshot 2023-05-02 at 2 49 53 PM" src="https://user-images.githubusercontent.com/1275592/235815143-1e0a0c75-69c8-40d7-9853-b1b6ca4a878a.png">

**Comment by Incin** [comment]
i double checked and this was intentional.
